stages:
  - test
  - build
  - sign
  - package

variables:
  CONTAINER_NAME: thethingsnetwork/gateway-connector-bridge

cache:
  paths:
    - /go/pkg/dep

before_script:
  - rm -rf $GOPATH
  - mkdir -p $GOPATH/src/github.com/TheThingsNetwork && ln -s $(pwd) $GOPATH/src/github.com/TheThingsNetwork/gateway-connector-bridge

tests:
  stage: test
  image: golang:1.11
  services:
    - thethingsnetwork/rabbitmq
    - redis
  variables:
    REDIS_HOST: redis
    MQTT_ADDRESS: thethingsnetwork__rabbitmq:1883
    AMQP_ADDRESS: thethingsnetwork__rabbitmq:5672
  script:
    - pushd $GOPATH/src/github.com/TheThingsNetwork/gateway-connector-bridge
    - make deps
    - make test
    - popd

binaries:
  stage: build
  image: golang:1.11
  script:
    - mkdir release
    - export CI_BUILD_DATE=$(date -u +%Y-%m-%dT%H:%M:%SZ)
    - echo "date $CI_BUILD_DATE" >> release/info
    - echo "commit $CI_BUILD_REF" >> release/info
    - pushd $GOPATH/src/github.com/TheThingsNetwork/gateway-connector-bridge
    - make deps
    - GOOS=linux GOARCH=386 make build
    - GOOS=linux GOARCH=amd64 make build
    - GOOS=linux GOARCH=arm make build
    - GOOS=darwin GOARCH=amd64 make build
    - GOOS=windows GOARCH=386 make build
    - GOOS=windows GOARCH=amd64 make build
    - popd
  artifacts:
    paths:
      - release/

sign:
  only:
    - tags
    - master@thethingsnetwork/gateway-connector-bridge
    - develop@thethingsnetwork/gateway-connector-bridge
  stage: sign
  image: golang:1.11
  script:
    - pushd release
    - shasum -a 256 $(ls) > checksums
    - mkdir ~/.gnupg && chmod 700 ~/.gnupg
    - echo -e "use-agent\npinentry-mode loopback" > ~/.gnupg/gpg.conf
    - echo "allow-loopback-pinentry" > ~/.gnupg/gpg-agent.conf
    - gpg --no-tty --batch --import /gpg/signing.ci.gpg-key
    - echo $GPG_PASSPHRASE | gpg --batch --no-tty --yes --passphrase-fd 0 --detach-sign checksums
    - popd
  artifacts:
    paths:
      - release/checksums
      - release/checksums.sig

gitlab-image:
  stage: package
  image: docker:git
  services:
    - "docker:dind"
  script:
    - docker build -t ttn .
    - docker login -u "gitlab-ci-token" -p "$CI_BUILD_TOKEN" registry.gitlab.com
    - docker tag ttn registry.gitlab.com/$CONTAINER_NAME:$CI_BUILD_REF_NAME
    - docker push registry.gitlab.com/$CONTAINER_NAME:$CI_BUILD_REF_NAME

dockerhub-image:
  only:
    - tags
    - master@thethingsnetwork/gateway-connector-bridge
    - develop@thethingsnetwork/gateway-connector-bridge
  stage: package
  image: docker:git
  services:
    - "docker:dind"
  script:
    - docker build -t ttn .
    - docker login -u "$DOCKERHUB_USER" -p "$DOCKERHUB_PASSWORD"
    - docker tag ttn $CONTAINER_NAME:$CI_BUILD_REF_NAME
    - docker push $CONTAINER_NAME:$CI_BUILD_REF_NAME
    - if [[ "$CI_BUILD_REF_NAME" == "master" ]]; then docker tag ttn $CONTAINER_NAME:latest && docker push $CONTAINER_NAME:latest; fi

azure-binaries:
  only:
    - tags
    - master@thethingsnetwork/gateway-connector-bridge
    - develop@thethingsnetwork/gateway-connector-bridge
  stage: package
  image: registry.gitlab.com/thethingsindustries/upload
  script:
    - cd release
    - export STORAGE_CONTAINER=gateway-connector-bridge STORAGE_KEY=$AZURE_STORAGE_KEY ZIP=true TGZ=true PREFIX=$CI_BUILD_REF_NAME/
    - upload *
