version: '2'
services:
  redis:
    image: redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - /data
  rabbitmq:
    image: thethingsnetwork/rabbitmq
    hostname: rabbitserver
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /var/lib/rabbitmq
  bridge:
    image: thethingsnetwork/gateway-connector-bridge
    hostname: bridge
    restart: always
    depends_on:
      - redis
      - rabbitmq
    ports:
      - "1700:1700/udp"
    environment:
      BRIDGE_UDP: :1700
      BRIDGE_REDIS_ADDRESS: redis:6379
      BRIDGE_AMQP: rabbitmq:5672
      BRIDGE_MQTT: disable
      BRIDGE_TTN_ROUTER: disable
      BRIDGE_BLACKLIST: https://ttn.fyi/blacklist.yml
      # BRIDGE_TTN_ROUTER: discovery.thethingsnetwork.org:1900/the-router-id
